
import { EventItem } from './types';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: '1',
    startTime: '08:30',
    duration: '',
    title: 'Registration Counters',
    description: `Intruducitnvg xandy Venue- front (intro)
Registration
Route
Students- Interview
Program Schedule
Venue arrangements
Marchendise
Mentors
JEE Exam
Food arrangements
LED Display
Food Counter Arrangements
mentors make sure students hampers`,
    teamLead: 'Najath',
    teamMembers: 'Vachan, Nazim, Aswani',
    logistics: 'Gift Packing, Cover, Sticker, Hosting Boys',
    notes: 'BDE Team 1-8 (15 Staffs, Faheem, Afther)',
    category: 'registration',
  },
  {
    id: '2',
    startTime: '08:30',
    duration: '',
    title: 'Welcome Drink',
    description: 'Ovio Team- 6',
    teamLead: 'Adhil Ahammed',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'food',
  },
  {
    id: '3',
    startTime: '08:30',
    duration: '',
    title: 'JEE Exam',
    description: 'Shamil Media, Sound',
    teamLead: 'Navas',
    teamMembers: 'Sabna, Aswathy',
    logistics: '',
    notes: '',
    category: 'general',
  },
  {
    id: '4',
    startTime: '08:30',
    duration: '',
    title: 'JEE Parents',
    description: 'Shamil Media',
    teamLead: 'Shafeer',
    teamMembers: 'Sindhu, Ruvitha, Binsha',
    logistics: 'Sound, Chair',
    notes: '',
    category: 'general',
  },
  {
    id: '5',
    startTime: '08:30',
    duration: '',
    title: 'XandY Waves',
    description: 'Ovio Videographer Media',
    teamLead: 'Navya',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'general',
  },
  {
    id: '6',
    startTime: '08:30',
    duration: '',
    title: 'Venue Arrangements',
    description: 'Venue front (intro), Route, Mentors, Food',
    teamLead: 'Sharbi',
    teamMembers: 'Hiba',
    logistics: '',
    notes: 'Students- Interview, Program Schedule, Merchandise',
    category: 'general',
  },
  {
    id: '7',
    startTime: '08:30',
    duration: '',
    title: 'LED Display',
    description: 'Testimonials, Videos',
    teamLead: 'Shafi',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '8',
    startTime: '08:30',
    duration: '',
    title: 'Food Counter Arrangements',
    description: 'Food, Coupon Counters (Print out), Drinking Points, Zaitoon Stalls (2)',
    teamLead: 'Yaseen',
    teamMembers: '',
    logistics: 'Electricity',
    notes: '',
    category: 'food',
  },
  {
    id: '9',
    startTime: '08:30',
    duration: '',
    title: 'Food Coupon for Staffs',
    description: 'Staff List (Print out)',
    teamLead: 'Sabiq',
    teamMembers: '',
    logistics: 'Coupons',
    notes: '',
    category: 'food',
  },
  {
    id: '10',
    startTime: '09:50',
    duration: '10 mns',
    title: 'Intro: Beyond Learning',
    description: 'PPT- Content, Design- Faheem',
    teamLead: 'Reem Eshal',
    teamMembers: '',
    logistics: '',
    script: 'Script by Faiza: "Welcome everyone to Beyond Learning, Towards Greatness..."',
    notes: 'Towards Greatness',
    category: 'stage',
  },
  {
    id: '11',
    startTime: '10:00',
    duration: '20 mns',
    title: 'Family Menti Quiz',
    description: 'Find the X & Y, Menti Quiz- Rauf, Questions- Mrudul, password list',
    teamLead: 'Niyas',
    teamMembers: 'Afther, Rauf',
    logistics: 'Join in Student name & Batch',
    notes: '',
    category: 'stage',
  },
  {
    id: '12',
    startTime: '10:20',
    duration: '2 mns',
    title: 'Anchor Intro',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Ladies and gentlemen, please connect to the WiFi using the password displayed on the screen.',
    notes: '',
    category: 'stage',
  },
  {
    id: '13',
    startTime: '10:22',
    duration: '10 mns',
    title: 'XandY Updates',
    description: 'PPT- Faheem, Add AI4Kerala',
    teamLead: 'Shafeer Ambatt',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '14',
    startTime: '10:32',
    duration: '5 mns',
    title: 'Anchor',
    description: `Parents Profiles- LED Wall
intro for this panelist
* Dr. Anas
* Dr. Smitha
* prasant
* Mirash`,
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Stage Arragments',
    script: 'Next up, we would like to showcase the incredible journey of our parents.',
    notes: '',
    category: 'stage',
  },
  {
    id: '15',
    startTime: '10:37',
    duration: '30 mns',
    title: 'Dr. Basil Session (Panel -1)',
    description: 'Guests: Dr. Anas, Dr. Smitha, F/O Parvana Prasanth',
    teamLead: 'Dr. Basil CP',
    teamMembers: '',
    logistics: 'Gift by Dr. Basil- XandY Kit',
    notes: '',
    category: 'stage',
  },
  {
    id: '16',
    startTime: '11:07',
    duration: '2 mns',
    title: 'Anchor',
    description: 'Thanking panel, Welcoming Dr. Kanniyan',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'stage arrangement',
    script: 'Thank you Dr. Basil for those insights. Please welcome Dr. Mohmd Kutty Kanniyan to the stage.',
    notes: '',
    category: 'stage',
  },
  {
    id: '17',
    startTime: '11:09',
    duration: '15 mns',
    title: 'Dr. Mohmd Kutty Kanniyan (Interactive Session)',
    description: '',
    teamLead: 'Dr. Kanniyan',
    teamMembers: '',
    logistics: 'Gift by Primrose',
    notes: '',
    category: 'stage',
  },
  {
    id: '18',
    startTime: '11:24',
    duration: '3 mns',
    title: 'Anchor',
    description: 'Purchase Rose- Navas',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'stage arrangement',
    script: 'Thank you Sir. We are now moving to one of the most exciting parts of the day.',
    notes: '',
    category: 'stage',
  },
  {
    id: '19',
    startTime: '11:27',
    duration: '30 mns',
    title: 'Launching: JEE, Parenting App, Olympiads',
    description: `Spin Wheel- Nazim, Shafi
Photoshoot of winners ( mentors make sure photography of candidate)`,
    teamLead: 'Shafeer',
    teamMembers: 'Najath, Ladheedha, Mehshan, Ziyan, Ajmal, Ahammed',
    logistics: 'LED, Spin Wheel',
    notes: '',
    category: 'stage',
  },
  {
    id: '20',
    startTime: '11:57',
    duration: '4 mns',
    title: 'Anchor',
    description: 'Nisar Pattuvam Video (No ppt)',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Pick and drop- Program day: Shafaf',
    script: 'We are now ready to present a special video feature from Nisar Pattuvam.',
    notes: '',
    category: 'stage',
  },
  {
    id: '21',
    startTime: '12:01',
    duration: '45 mns',
    title: 'Nisar Pattuvam',
    description: 'LED Wall- Grpahics',
    teamLead: 'Nisar Pattuvam',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '22',
    startTime: '12:46',
    duration: '2 mns',
    title: 'Anchor',
    description: `Pattuvan Session Conclusion - Roshan

Ladheedha Nasrin KA
Hannath beevi kk
Neethu Babu`,
    teamLead: 'Anchor', // Inferred as it's an anchor slot despite missing data in CSV column E
    teamMembers: '',
    logistics: 'stage arrangement',
    script: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '23',
    startTime: '12:48',
    duration: '4 mns',
    title: 'Stage Setting / Mentors Video',
    description: 'Mentors gathering duty- Fameena',
    teamLead: 'Fameena',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '24',
    startTime: '12:52',
    duration: '20 mns',
    title: 'Ladheedha, Neethu, Hanna (Panel -2 )',
    description: '',
    teamLead: 'Ladheedha',
    teamMembers: 'Neethu, Hanna',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '25',
    startTime: '01:12',
    duration: '2 mns',
    title: 'Anchor',
    description: ``,
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Gift by Fawaz OP // stage arrangement',
    script: 'A big round of applause! We would like to invite Fawaz OP to present a token of appreciation.',
    notes: '',
    category: 'stage',
  },
  {
    id: '26',
    startTime: '01:14',
    duration: '30 mns',
    title: 'Rishiraj Singh',
    description: '',
    teamLead: 'Rishiraj Singh',
    teamMembers: '',
    logistics: 'Gift by a student- Rose, Pick and drop night- Haris Pattalam, Sabiq',
    notes: '',
    category: 'stage',
  },
  {
    id: '27',
    startTime: '01:44',
    duration: '7 mns',
    title: 'Anchor',
    description: 'M. Jouhar, principal,Peace Public School,Kottakkal, Nishad Pullampalavan, Principal, The Ideal Global Residential Higher Secondary School, Dharmagiri, Dr.Najeeb Mohamed , Director , Ansar English School , Perumpilavu if possible 5 minutes testimonial principle',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'What an amazing launch! Now, get your thinking caps on for Mrudul.',
    notes: '',
    category: 'stage',
  },
  {
    id: '28',
    startTime: '01:51',
    duration: '5 mns',
    title: 'Single Talks Jafar TT',
    description: 'Intro, Video',
    teamLead: 'Jafar TT',
    teamMembers: '',
    logistics: 'Gift by Fawaz OP',
    notes: '',
    category: 'stage',
  },
  {
    id: '29',
    startTime: '01:56',
    duration: '5 mns',
    title: 'Anchor',
    description: 'Anchor',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '30',
    startTime: '02:01',
    duration: '5 mns',
    title: 'Single Talk by Farseen Ali',
    description: 'Gift By Premrose sir',
    teamLead: 'Farseen Ali',
    teamMembers: '',
    logistics: 'Gift By Primrose',
    notes: '',
    category: 'stage',
  },
  {
    id: '31',
    startTime: '02:06',
    duration: '5 mns',
    title: 'Anchor',
    description: 'Student Arragement final call',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '32',
    startTime: '02:11',
    duration: '30 mns',
    title: 'Awards',
    description: 'XIQ, NSMC, Menti League, Schools',
    teamLead: 'Faculty Team',
    teamMembers: '',
    logistics: 'School Principals Testimonial (Ansar EM, Peace, Ideal)',
    notes: 'Gift by Ajmal, Fawaz, Niyas, Primrose',
    category: 'stage',
  },
  {
    id: '33',
    startTime: '02:41',
    duration: '2 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Congratulations to all winners. Please welcome Babu Ramachandran.',
    notes: '',
    category: 'stage',
  },
  {
    id: '34',
    startTime: '02:43',
    duration: '45 mns',
    title: 'Babu Ramachandran',
    description: `30 minutes - talk 
15 - interaction
with ppt`,
    teamLead: 'Babu Ramachandran',
    teamMembers: '',
    logistics: 'Gift by Primrose',
    notes: 'Pick and drop- Program day: Haris Pattalam',
    category: 'stage',
  },
  {
    id: '35',
    startTime: '03:28',
    duration: '3 mns',
    title: 'Anchor',
    description: 'Thanking Babu Ramachandran,Babu Rama Session Conclusion - Roshan',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Thank you Sir. We are now entering our final panel discussion.',
    notes: '',
    category: 'stage',
  },
  {
    id: '36',
    startTime: '03:31',
    duration: '30 mns',
    title: 'Ajmal C',
    description: 'Closing Session\n- love note ',
    teamLead: 'Ajmal C',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '37',
    startTime: '04:01',
    duration: '2 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Stage Arragements',
    notes: '',
    category: 'stage',
  },
  {
    id: '38',
    startTime: '04:03',
    duration: '48 mns',
    title: 'Mrudul M Mahesh',
    description: 'Stage Setting, Mrudul\'s Video - six candidates',
    teamLead: 'Mrudul M Mahesh',
    teamMembers: '',
    logistics: 'Quiz, Gift Presentation ',
    notes: '',
    category: 'stage',
  },
  {
    id: '39',
    startTime: '04:51',
    duration: '5 mns',
    title: 'End',
    description: 'Vote of thanks',
    teamLead: 'XandY Teams',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'general',
  },
  {
    id: '40',
    startTime: '04:56',
    duration: '2 mns',
    title: 'Anchor',
    description: 'Closing',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'That concludes our sessions. Thank you all for being part of Beyond Learning.',
    notes: '',
    category: 'stage',
  },
];
