
import { EventItem } from './types';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: '1',
    startTime: '08:30',
    duration: '',
    title: 'Registration',
    description: 'Registration Counters',
    teamLead: 'Najath',
    teamMembers: 'Vachan, Nazim, Aswani',
    logistics: 'Gift Packing, Cover, Sticker, Hosting Boys',
    notes: 'BDE Team 1-8 (15 Staffs, Faheem, Afther)',
    category: 'registration',
  },
  {
    id: '2',
    startTime: '08:30',
    duration: '',
    title: 'Welcome Drink',
    description: 'Ovio Team- 6',
    teamLead: 'Adhil Ahammed',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'food',
  },
  {
    id: '3',
    startTime: '08:30',
    duration: '',
    title: 'JEE Exam',
    description: 'Shamil Media, Sound',
    teamLead: 'Navas',
    teamMembers: 'Sabna, Aswathy',
    logistics: '',
    notes: '',
    category: 'general',
  },
  {
    id: '4',
    startTime: '08:30',
    duration: '',
    title: 'JEE Parents',
    description: 'Shamil Media',
    teamLead: 'Shafeer',
    teamMembers: 'Sindhu, Ruvitha, Binsha',
    logistics: 'Sound, Chair',
    notes: '',
    category: 'general',
  },
  {
    id: '5',
    startTime: '08:30',
    duration: '',
    title: 'XandY Waves',
    description: 'Ovio Videographer Media',
    teamLead: 'Navya',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'general',
  },
  {
    id: '6',
    startTime: '08:30',
    duration: '',
    title: 'Venue Arrangements',
    description: 'Venue front (intro), Route, Mentors, Food',
    teamLead: 'Sharbi',
    teamMembers: 'Hiba',
    logistics: '',
    notes: 'Students- Interview, Program Schedule, Merchandise',
    category: 'general',
  },
  {
    id: '7',
    startTime: '08:30',
    duration: '',
    title: 'LED Display',
    description: 'Testimonials, Videos',
    teamLead: 'Shafi',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '8',
    startTime: '08:30',
    duration: '',
    title: 'Food Counter Arrangements',
    description: 'Food, Coupon Counters (Print out), Drinking Points, Zaitoon Stalls (2)',
    teamLead: 'Yaseen',
    teamMembers: '',
    logistics: 'Electricity',
    notes: '',
    category: 'food',
  },
  {
    id: '9',
    startTime: '08:30',
    duration: '',
    title: 'Food Coupon for Staffs',
    description: 'Staff List (Print out)',
    teamLead: 'Sabiq',
    teamMembers: '',
    logistics: 'Coupons',
    notes: '',
    category: 'food',
  },
  {
    id: '10',
    startTime: '09:50',
    duration: '10 mns',
    title: 'Intro: Beyond Learning',
    description: 'PPT- Content, Design- Faheem',
    teamLead: 'Reem Eshal',
    teamMembers: '',
    logistics: '',
    script: 'Script by Faiza: "Welcome everyone to Beyond Learning, Towards Greatness..."',
    notes: 'Towards Greatness',
    category: 'stage',
  },
  {
    id: '11',
    startTime: '10:00',
    duration: '20 mns',
    title: 'Family Menti Quiz',
    description: 'Find the X & Y, Menti Quiz- Rauf, Questions- Mrudul',
    teamLead: 'Niyas',
    teamMembers: 'Afther, Rauf',
    logistics: 'Join in Student name & Batch',
    notes: '',
    category: 'stage',
  },
  {
    id: '12',
    startTime: '10:20',
    duration: '2 mns',
    title: 'Anchor Intro',
    description: 'Wifi password in 1st slide',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Ladies and gentlemen, please connect to the WiFi using the password displayed on the screen.',
    notes: '',
    category: 'stage',
  },
  {
    id: '13',
    startTime: '10:22',
    duration: '10 mns',
    title: 'XandY Updates',
    description: 'PPT- Faheem, Add AI4Kerala',
    teamLead: 'Shafeer Ambatt',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '14',
    startTime: '10:32',
    duration: '5 mns',
    title: 'Anchor',
    description: 'Parents Profiles- LED Wall',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Next up, we would like to showcase the incredible journey of our parents.',
    notes: '',
    category: 'stage',
  },
  {
    id: '15',
    startTime: '10:40',
    duration: '35 mns',
    title: 'Dr. Basil Session',
    description: 'Guests: Dr. Anas, Dr. Smitha, F/O Parvana Prasanth',
    teamLead: 'Dr. Basil CP',
    teamMembers: '',
    logistics: 'Gift by Dr. Basil- XandY Kit',
    notes: '',
    category: 'stage',
  },
  {
    id: '16',
    startTime: '11:15',
    duration: '2 mns',
    title: 'Anchor',
    description: 'Thanking panel, Welcoming Dr. Kanniyan',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Thank you Dr. Basil for those insights. Please welcome Dr. Mohmd Kutty Kanniyan to the stage.',
    notes: '',
    category: 'stage',
  },
  {
    id: '17',
    startTime: '11:17',
    duration: '15 mns',
    title: 'Dr. Mohmd Kutty Kanniyan',
    description: '',
    teamLead: 'Dr. Kanniyan',
    teamMembers: '',
    logistics: 'Gift by Primrose',
    notes: '',
    category: 'stage',
  },
  {
    id: '18',
    startTime: '11:32',
    duration: '4 mns',
    title: 'Stage Setting / Mentors Video',
    description: 'Mentors gathering duty- Fameena',
    teamLead: 'Fameena',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '19',
    startTime: '11:36',
    duration: '20 mns',
    title: 'Ladheedha, Neethu, Hanna',
    description: '',
    teamLead: 'Ladheedha',
    teamMembers: 'Neethu, Hanna',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '20',
    startTime: '11:56',
    duration: '4 mns',
    title: 'Anchor',
    description: 'Nisar Pattuvam Video',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Pick and drop- Program day: Shafaf',
    script: 'We are now ready to present a special video feature from Nisar Pattuvam.',
    notes: '',
    category: 'stage',
  },
  {
    id: '21',
    startTime: '12:00',
    duration: '45 mns',
    title: 'Nisar Pattuvam',
    description: 'LED Wall- Grpahics',
    teamLead: 'Nisar Pattuvam',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
  {
    id: '22',
    startTime: '12:45',
    duration: '2 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Gift by Fawaz OP',
    script: 'A big round of applause! We would like to invite Fawaz OP to present a token of appreciation.',
    notes: '',
    category: 'stage',
  },
  {
    id: '23',
    startTime: '12:47',
    duration: '30 mns',
    title: 'Rishiraj Singh',
    description: '',
    teamLead: 'Rishiraj Singh',
    teamMembers: '',
    logistics: 'Gift by a student- Rose, Pick and drop night- Haris Pattalam, Sabiq',
    notes: '',
    category: 'stage',
  },
  {
    id: '24',
    startTime: '01:17',
    duration: '3 mns',
    title: 'Anchor',
    description: 'Purchase Rose- Navas',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Pick and drop- Program day: Sabiq',
    script: 'Thank you Sir. We are now moving to one of the most exciting parts of the day.',
    notes: '',
    category: 'stage',
  },
  {
    id: '25',
    startTime: '01:20',
    duration: '30 mns',
    title: 'Launching: JEE, Parenting App, Olympiads',
    description: 'Spin Wheel- Nazim, Shafi',
    teamLead: 'Shafeer',
    teamMembers: 'Najath, Ladheedha, Mehshan, Ziyan, Ajmal, Ahammed',
    logistics: 'LED, Spin Wheel',
    notes: '',
    category: 'stage',
  },
  {
    id: '26',
    startTime: '01:50',
    duration: '2 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'What an amazing launch! Now, get your thinking caps on for Mrudul.',
    notes: '',
    category: 'stage',
  },
  {
    id: '27',
    startTime: '01:52',
    duration: '48 mns',
    title: 'Mrudul M Mahesh',
    description: "Stage Setting, Mrudul's Video",
    teamLead: 'Mrudul M Mahesh',
    teamMembers: '',
    logistics: 'Quiz',
    notes: '',
    category: 'stage',
  },
  {
    id: '28',
    startTime: '02:40',
    duration: '5 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: 'Gift by Yaseen',
    script: 'Thank you Mrudul. We will now proceed to the awards ceremony.',
    notes: '',
    category: 'stage',
  },
  {
    id: '29',
    startTime: '02:45',
    duration: '30 mns',
    title: 'Awards',
    description: 'IOQM, XIQ, NSMC, Menti League, Schools',
    teamLead: 'Faculty Team',
    teamMembers: '',
    logistics: 'School Principals Testimonial (Ansar EM, Peace, Ideal)',
    notes: 'Gift by Ajmal, Fawaz, Niyas, Primrose',
    category: 'stage',
  },
  {
    id: '30',
    startTime: '03:15',
    duration: '2 mns',
    title: 'Anchor',
    description: '',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Congratulations to all winners. Please welcome Babu Ramachandran.',
    notes: '',
    category: 'stage',
  },
  {
    id: '31',
    startTime: '03:17',
    duration: '45 mns',
    title: 'Babu Ramachandran',
    description: '',
    teamLead: 'Babu Ramachandran',
    teamMembers: '',
    logistics: 'Gift by Primrose',
    notes: 'Pick and drop- Program day: Haris Pattalam',
    category: 'stage',
  },
  {
    id: '32',
    startTime: '04:02',
    duration: '3 mns',
    title: 'Anchor',
    description: 'Thanking Babu Ramachandran, Inviting Panellists',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'Thank you Sir. We are now entering our final panel discussion.',
    notes: '',
    category: 'stage',
  },
  {
    id: '33',
    startTime: '04:05',
    duration: '25 mns',
    title: 'Panel: Jafar TT, Farseen Ali, Fawaz OP',
    description: 'Intro, Video',
    teamLead: 'Jafar TT',
    teamMembers: 'Farseen Ali, Fawaz OP',
    logistics: 'Gift by Fawaz OP',
    notes: '',
    category: 'stage',
  },
  {
    id: '34',
    startTime: '04:30',
    duration: '2 mns',
    title: 'Anchor',
    description: 'Closing',
    teamLead: 'Anchor',
    teamMembers: '',
    logistics: '',
    script: 'That concludes our sessions. Thank you all for being part of Beyond Learning.',
    notes: '',
    category: 'stage',
  },
  {
    id: '35',
    startTime: '04:32',
    duration: '28 mns',
    title: 'Ajmal C',
    description: 'Closing Session',
    teamLead: 'Ajmal C',
    teamMembers: '',
    logistics: '',
    notes: '',
    category: 'stage',
  },
];
